version: '3.4'

services:
  api:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3030:3030
      - 5022:5022
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on: 
      - sqlserver

  sqlserver:
    image: mcr.microsoft.com/mssql/server
    ports:
      - 3306
    environment: 
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "Password_123"
      MSSQL_PID: "Express"

