version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5030:5030
      - 5031:5031
    environment: 
        ASPNETCORE_ENVIRONMENT: Development

  db: 
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
       MYSQL_ROOT_PASSWORD: example
       MYSQL_USER: @speedgovernor

       
  adminer:
    image: adminer
    restart: always
    ports:
      - 8083:8080
