version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}api
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 5022:5022
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  mysql_speedgovernor:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - 3306
    volumes:
      - mysql_db_data:/var/lib/mysql
    healthcheck:
       test: out=$$(mysqladmin ping -h localhost -P 3306 -u root --password=rootpassword 2>&1); echo $$out | grep 'mysqld is alive' || { echo $$out; exit 1; }

  adminer_container:
    image: adminer:latest
    environment:
      ADMINER_DEFAULT_SERVER: mysql_speedgovernor
    ports:
      - 9000:8080

volumes:
  mysql_db_data:

